/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
extern int Magic = 111;
extern bool CloseAllNow = FALSE;
extern string moneymanagement = "Money Management";
extern double BuyLots = 0.1;
extern double SellLots = 0.1;
extern bool MM = FALSE;
extern double BuyRisk = 2.0;
extern double SellRisk = 2.0;
int gi_128 = 1;
extern double MinLot = 0.1;
extern double MaxLot = 1.0;
extern int LotDigits = 2;
extern string ordersmanagement = "Order Management";
extern int StopLoss = 0;
extern int TakeProfit = 30;
extern bool ConstantStop = FALSE;
extern int Step1 = 30;
extern int TP1 = 30;
extern double Multiplier1 = 2.0;
extern int Step2 = 30;
extern int TP2 = 30;
extern double Multiplier2 = 2.0;
extern int Step3 = 30;
extern int TP3 = 30;
extern double Multiplier3 = 2.0;
extern int Step4 = 30;
extern int TP4 = 30;
extern double Multiplier4 = 2.0;
extern int Step5 = 30;
extern int TP5 = 30;
extern double Multiplier5 = 2.0;
extern int Step6 = 30;
extern int TP6 = 30;
extern double Multiplier6 = 2.0;
extern int Step7 = 30;
extern int TP7 = 30;
extern double Multiplier7 = 2.0;
extern int Step8 = 30;
extern int TP8 = 30;
extern double Multiplier8 = 2.0;
extern int Step9 = 30;
extern int TP9 = 30;
extern double Multiplier9 = 2.0;
extern int Step10 = 30;
extern int TP10 = 30;
extern double Multiplier10 = 2.0;
extern int Step11 = 30;
extern int TP11 = 30;
extern double Multiplier11 = 2.0;
extern int Step12 = 30;
extern int TP12 = 30;
extern double Multiplier12 = 2.0;
extern int Step13 = 30;
extern int TP13 = 30;
extern double Multiplier13 = 2.0;
extern int Step14 = 30;
extern int TP14 = 30;
extern double Multiplier14 = 2.0;
extern int Step15 = 30;
extern int TP15 = 30;
extern double Multiplier15 = 2.0;
extern int Step16 = 30;
extern int TP16 = 30;
extern double Multiplier16 = 2.0;
extern int Step17 = 30;
extern int TP17 = 30;
extern double Multiplier17 = 2.0;
extern int Step18 = 30;
extern int TP18 = 30;
extern double Multiplier18 = 2.0;
extern int Step19 = 30;
extern int TP19 = 30;
extern double Multiplier19 = 2.0;
extern int Step20 = 30;
extern int TP20 = 30;
extern double Multiplier20 = 2.0;
extern int Slippage = 3;
extern string entrylogics = "Entry Settins";
extern bool UseMACD = FALSE;
extern int MACDFast = 14;
extern int MACDSlow = 26;
extern int MACDSMA = 9;
extern string timefilter = "Time Filter";
extern int StartHour = 0;
extern int EndHour = 24;
extern int FridayCloseTime = 20;
double gd_540;
double gd_548;
double g_price_556;
double g_price_564;
double g_lots_572;
double g_price_580;
double gd_588;
double gd_596;
int g_ord_total_604;
int g_digits_608;
int gi_612;
int g_ticket_616;
int g_bool_620;

int init() {
   g_digits_608 = Digits;
   if (g_digits_608 == 3 || g_digits_608 == 5) {
      gd_540 = 10.0 * Point;
      gd_548 = 10;
   } else {
      gd_540 = Point;
      gd_548 = 1;
   }
   return (1);
}

int start() {
   if (count(OP_BUY) + count(OP_SELL) == 0) {
      BuyLots = NormalizeDouble(AccountBalance() / 1000.0 / 100.0 * BuyRisk, LotDigits);
      SellLots = NormalizeDouble(AccountBalance() / 1000.0 / 100.0 * SellRisk, LotDigits);
      if (BuyLots < MinLot) BuyLots = MinLot;
      if (SellLots < MinLot) SellLots = MinLot;
      if (BuyLots > MaxLot) BuyLots = MaxLot;
      if (SellLots > MaxLot) SellLots = MaxLot;
   }
   if (CloseAllNow == TRUE) {
      for (g_ord_total_604 = OrdersTotal(); g_ord_total_604 >= 0; g_ord_total_604--) {
         OrderSelect(g_ord_total_604, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() == Symbol() || gi_128 == 3 && OrderMagicNumber() == Magic) {
            if (OrderType() == OP_BUY || OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), OrderClosePrice(), 5, CLR_NONE);
            if (OrderType() != OP_BUY && OrderType() != OP_SELL) OrderDelete(OrderTicket());
         }
      }
      return (0);
   }
   int l_ticket_0 = 0;
   int l_ticket_4 = 0;
   int l_ticket_8 = 0;
   int l_ticket_12 = 0;
   double l_ord_lots_16 = 0;
   double l_ord_lots_24 = 0;
   double l_ord_lots_32 = 0;
   double l_ord_lots_40 = 0;
   double l_ord_lots_48 = 0;
   double l_ord_lots_56 = 0;
   double l_ord_open_price_64 = 0;
   double l_ord_open_price_72 = 0;
   double l_ord_takeprofit_80 = 0;
   double l_ord_takeprofit_88 = 0;
   double ld_96 = 0;
   double ld_104 = 0;
   string ls_112 = "";
   string ls_120 = "";
   string ls_128 = "";
   string ls_136 = "";
   string ls_144 = "";
   string ls_152 = "";
   string ls_160 = "";
   string ls_168 = "";
   string ls_176 = "";
   if (iMACD(NULL, 0, MACDFast, MACDSlow, MACDSMA, PRICE_CLOSE, MODE_MAIN, 0) > iMACD(NULL, 0, MACDFast, MACDSlow, MACDSMA, PRICE_CLOSE, MODE_MAIN, 1)) gi_612 = 2;
   if (iMACD(NULL, 0, MACDFast, MACDSlow, MACDSMA, PRICE_CLOSE, MODE_MAIN, 0) < iMACD(NULL, 0, MACDFast, MACDSlow, MACDSMA, PRICE_CLOSE, MODE_MAIN, 1)) gi_612 = 1;
   for (g_ord_total_604 = 0; g_ord_total_604 < OrdersTotal(); g_ord_total_604++) {
      OrderSelect(g_ord_total_604, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() || gi_128 == 3 && OrderMagicNumber() == Magic) {
         if (OrderType() == OP_BUY && l_ticket_0 < OrderTicket()) {
            l_ord_lots_16 = OrderLots();
            l_ord_open_price_64 = OrderOpenPrice();
            l_ticket_0 = OrderTicket();
            l_ord_takeprofit_88 = OrderTakeProfit();
         }
         if (OrderType() == OP_BUY) {
            if (OrderLots() < l_ord_lots_48 || l_ord_lots_48 == 0.0) {
               l_ord_lots_48 = OrderLots();
               ld_96 = OrderOpenPrice() - StopLoss * gd_540;
            }
         }
         if (OrderType() == OP_SELL && l_ticket_4 < OrderTicket()) {
            l_ord_lots_24 = OrderLots();
            l_ord_open_price_72 = OrderOpenPrice();
            l_ticket_4 = OrderTicket();
            l_ord_takeprofit_80 = OrderTakeProfit();
         }
         if (OrderType() == OP_SELL) {
            if (OrderLots() < l_ord_lots_56 || l_ord_lots_56 == 0.0) {
               l_ord_lots_56 = OrderLots();
               ld_104 = OrderOpenPrice() + StopLoss * gd_540;
            }
         }
         if (OrderType() == OP_BUYLIMIT) {
            l_ticket_8 = OrderTicket();
            l_ord_lots_32 = OrderLots();
         }
         if (OrderType() == OP_SELLLIMIT) {
            l_ticket_12 = OrderTicket();
            l_ord_lots_40 = OrderLots();
         }
      }
   }
   if (l_ticket_0 == 0 && l_ticket_8 != 0) OrderDelete(l_ticket_8);
   if (l_ticket_0 == 0 && l_ticket_8 == 0) {
      g_price_556 = Ask - StopLoss * gd_540;
      if (StopLoss <= 0) g_price_556 = 0;
      g_price_564 = Ask + TakeProfit * gd_540;
      if ((StartHour < EndHour && TimeHour(TimeCurrent()) >= StartHour && TimeHour(TimeCurrent()) < EndHour) || (StartHour > EndHour && TimeHour(TimeCurrent()) >= StartHour ||
         TimeHour(TimeCurrent()) < EndHour)) {
         if (DayOfWeek() != 5 || Hour() < FridayCloseTime) {
            if ((gi_612 == 2 && l_ticket_4 == 0) || UseMACD == FALSE) {
               if (AccountFreeMarginCheck(Symbol(), OP_BUY, BuyLots) >= 0.0) {
                  if (gi_128 != 2 && gi_128 != 3) OrderSend(Symbol(), OP_BUY, BuyLots, Ask, Slippage * gd_548, g_price_556, g_price_564, "", Magic, 0, CLR_NONE);
                  else {
                     g_ticket_616 = OrderSend(Symbol(), OP_BUY, BuyLots, Ask, Slippage * gd_548, 0, 0, "", Magic, 0, CLR_NONE);
                     g_bool_620 = OrderModify(g_ticket_616, OrderOpenPrice(), g_price_556, g_price_564, 0, CLR_NONE);
                     if (g_bool_620 == FALSE) Print("Error modifying BUY order : ", GetLastError());
                  }
               } else {
                  if (AccountFreeMarginCheck(Symbol(), OP_BUY, BuyLots) >= 0.0) ls_176 = "we recommend you to decrease your start lot or increase deposit";
                  else ls_128 = "BUY," + DoubleToStr(BuyLots, 2) + " lots. ";
               }
            }
         }
      }
   }
   if (l_ticket_4 == 0 && l_ticket_12 != 0) OrderDelete(l_ticket_12);
   if (l_ticket_4 == 0 && l_ticket_12 == 0) {
      g_price_556 = Bid + StopLoss * gd_540;
      if (StopLoss <= 0) g_price_556 = 0;
      g_price_564 = Bid - TakeProfit * gd_540;
      if ((StartHour < EndHour && TimeHour(TimeCurrent()) >= StartHour && TimeHour(TimeCurrent()) < EndHour) || (StartHour > EndHour && TimeHour(TimeCurrent()) >= StartHour ||
         TimeHour(TimeCurrent()) < EndHour)) {
         if (DayOfWeek() != 5 || Hour() < FridayCloseTime) {
            if ((gi_612 == 1 && l_ticket_0 == 0) || UseMACD == FALSE) {
               if (AccountFreeMarginCheck(Symbol(), OP_SELL, SellLots) >= 0.0) {
                  if (gi_128 != 2 && gi_128 != 3) OrderSend(Symbol(), OP_SELL, SellLots, Bid, Slippage * gd_548, g_price_556, g_price_564, "", Magic, 0, CLR_NONE);
                  else {
                     g_ticket_616 = OrderSend(Symbol(), OP_SELL, SellLots, Bid, Slippage * gd_548, 0, 0, "", Magic, 0, CLR_NONE);
                     g_bool_620 = OrderModify(g_ticket_616, OrderOpenPrice(), g_price_556, g_price_564, 0, CLR_NONE);
                     if (g_bool_620 == FALSE) Print("Error modifying SELL order : ", GetLastError());
                  }
               } else {
                  if (AccountFreeMarginCheck(Symbol(), OP_SELL, SellLots) >= 0.0) ls_176 = "we recommend you to decrease your start lot or increase deposit";
                  else ls_136 = "SELL," + DoubleToStr(SellLots, 2) + " lots. ";
               }
            }
         }
      }
   }
   if (l_ticket_0 != 0 && l_ticket_8 != 0) {
      if (AccountFreeMarginCheck(Symbol(), OP_BUY, l_ord_lots_32) < 0.0) {
         ls_160 = "BUYLIMIT," + DoubleToStr(l_ord_lots_32, 2) + " lots. ";
         OrderDelete(l_ticket_8);
      }
   }
   if (l_ticket_0 != 0 && l_ticket_8 == 0) {
      if (AccountFreeMarginCheck(Symbol(), OP_BUY, FinalMultiplier(NormalizeDouble(l_ord_lots_16 / l_ord_lots_48, 0)) * l_ord_lots_16) >= 0.0) {
         gd_596 = FinalStep(NormalizeDouble(l_ord_lots_16 / l_ord_lots_48, 0));
         gd_588 = FinalTP(NormalizeDouble(l_ord_lots_16 / l_ord_lots_48, 0));
         g_price_580 = l_ord_open_price_64 - gd_596 * gd_540;
         if (ConstantStop == FALSE) g_price_556 = g_price_580 - StopLoss * gd_540;
         else g_price_556 = ld_96;
         if (StopLoss <= 0) g_price_556 = 0;
         g_price_564 = g_price_580 + gd_588 * gd_540;
         g_lots_572 = NormalizeDouble(FinalMultiplier(NormalizeDouble(l_ord_lots_16 / l_ord_lots_48, 0)) * l_ord_lots_16, LotDigits);
         OrderSend(Symbol(), OP_BUYLIMIT, g_lots_572, g_price_580, Slippage * gd_548, g_price_556, g_price_564, "", Magic, 0, CLR_NONE);
      } else ls_144 = "BUYLIMIT," + DoubleToStr(2.0 * l_ord_lots_16, 2) + " lots. ";
   }
   if (l_ticket_4 != 0 && l_ticket_12 != 0) {
      if (AccountFreeMarginCheck(Symbol(), OP_SELL, l_ord_lots_40) < 0.0) {
         ls_168 = "SELLLIMIT," + DoubleToStr(l_ord_lots_40, 2) + " lots. ";
         OrderDelete(l_ticket_12);
      }
   }
   if (l_ticket_4 != 0 && l_ticket_12 == 0) {
      if (AccountFreeMarginCheck(Symbol(), OP_SELL, FinalMultiplier(NormalizeDouble(l_ord_lots_24 / l_ord_lots_56, 0)) * l_ord_lots_24) >= 0.0) {
         gd_596 = FinalStep(NormalizeDouble(l_ord_lots_24 / l_ord_lots_56, 0));
         gd_588 = FinalTP(NormalizeDouble(l_ord_lots_24 / l_ord_lots_56, 0));
         g_price_580 = l_ord_open_price_72 + gd_596 * gd_540;
         if (ConstantStop == FALSE) g_price_556 = g_price_580 + StopLoss * gd_540;
         else g_price_556 = ld_104;
         if (StopLoss <= 0) g_price_556 = 0;
         g_price_564 = g_price_580 - gd_588 * gd_540;
         g_lots_572 = NormalizeDouble(FinalMultiplier(NormalizeDouble(l_ord_lots_24 / l_ord_lots_56, 0)) * l_ord_lots_24, LotDigits);
         OrderSend(Symbol(), OP_SELLLIMIT, g_lots_572, g_price_580, Slippage * gd_548, g_price_556, g_price_564, "", Magic, 0, CLR_NONE);
      } else ls_152 = "SELLLIMIT," + DoubleToStr(2.0 * l_ord_lots_24, 2) + " lots. ";
   }
   for (g_ord_total_604 = 0; g_ord_total_604 < OrdersTotal(); g_ord_total_604++) {
      OrderSelect(g_ord_total_604, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol() || gi_128 == 3 && OrderType() == OP_BUY && l_ticket_0 != 0 && OrderMagicNumber() == Magic) {
         if (ConstantStop == FALSE) g_price_556 = l_ord_open_price_64 - StopLoss * gd_540;
         else g_price_556 = ld_96;
         if (StopLoss <= 0) g_price_556 = 0;
         if (l_ticket_0 > OrderTicket()) g_price_564 = l_ord_takeprofit_88;
         else g_price_564 = OrderTakeProfit();
         if (g_price_564 != OrderTakeProfit() || g_price_556 != OrderStopLoss()) OrderModify(OrderTicket(), OrderOpenPrice(), g_price_556, g_price_564, 0, CLR_NONE);
      }
      if (OrderSymbol() == Symbol() || gi_128 == 3 && OrderType() == OP_SELL && l_ticket_4 != 0 && OrderMagicNumber() == Magic) {
         if (ConstantStop == FALSE) g_price_556 = l_ord_open_price_72 + StopLoss * gd_540;
         else g_price_556 = ld_104;
         if (StopLoss <= 0) g_price_556 = 0;
         if (l_ticket_4 > OrderTicket()) g_price_564 = l_ord_takeprofit_80;
         else g_price_564 = OrderTakeProfit();
         if (g_price_564 != OrderTakeProfit() || g_price_556 != OrderStopLoss()) OrderModify(OrderTicket(), OrderOpenPrice(), g_price_556, g_price_564, 0, CLR_NONE);
      }
   }
   if (ls_128 != "" || ls_136 != "" || ls_144 != "" || ls_152 != "" || ls_160 != "" || ls_168 != "") ls_112 = "Not enough margin for opening orders: ";
   Comment(ls_120, 
      "\n", ls_112, ls_128, ls_136, ls_144, ls_152, ls_160, ls_168, 
   "\n", ls_176);
   return (0);
}

double FinalMultiplier(double ad_0) {
   switch (ad_0) {
   case 1.0:
      return (Multiplier1);
   case 2.0:
      return (Multiplier2);
   case 4.0:
      return (Multiplier3);
   case 8.0:
      return (Multiplier4);
   case 16.0:
      return (Multiplier5);
   case 32.0:
      return (Multiplier6);
   case 64.0:
      return (Multiplier7);
   case 128.0:
      return (Multiplier8);
   case 256.0:
      return (Multiplier9);
   case 512.0:
      return (Multiplier10);
   case 1024.0:
      return (Multiplier11);
   case 2048.0:
      return (Multiplier12);
   case 4096.0:
      return (Multiplier13);
   case 8192.0:
      return (Multiplier14);
   case 16384.0:
      return (Multiplier15);
   case 32768.0:
      return (Multiplier16);
   case 65536.0:
      return (Multiplier17);
   case 131072.0:
      return (Multiplier18);
   case 262144.0:
      return (Multiplier19);
   case 524288.0:
      return (Multiplier20);
   }
   return (Step20);
}

int FinalStep(double ad_0) {
   switch (ad_0) {
   case 1.0:
      return (Step1);
   case 2.0:
      return (Step2);
   case 4.0:
      return (Step3);
   case 8.0:
      return (Step4);
   case 16.0:
      return (Step5);
   case 32.0:
      return (Step6);
   case 64.0:
      return (Step7);
   case 128.0:
      return (Step8);
   case 256.0:
      return (Step9);
   case 512.0:
      return (Step10);
   case 1024.0:
      return (Step11);
   case 2048.0:
      return (Step12);
   case 4096.0:
      return (Step13);
   case 8192.0:
      return (Step14);
   case 16384.0:
      return (Step15);
   case 32768.0:
      return (Step16);
   case 65536.0:
      return (Step17);
   case 131072.0:
      return (Step18);
   case 262144.0:
      return (Step19);
   case 524288.0:
      return (Step20);
   }
   return (Step20);
}

int FinalTP(double ad_0) {
   switch (ad_0) {
   case 1.0:
      return (TP1);
   case 2.0:
      return (TP2);
   case 4.0:
      return (TP3);
   case 8.0:
      return (TP4);
   case 16.0:
      return (TP5);
   case 32.0:
      return (TP6);
   case 64.0:
      return (TP7);
   case 128.0:
      return (TP8);
   case 256.0:
      return (TP9);
   case 512.0:
      return (TP10);
   case 1024.0:
      return (TP11);
   case 2048.0:
      return (TP12);
   case 4096.0:
      return (TP13);
   case 8192.0:
      return (TP14);
   case 16384.0:
      return (TP15);
   case 32768.0:
      return (TP16);
   case 65536.0:
      return (TP17);
   case 131072.0:
      return (TP18);
   case 262144.0:
      return (TP19);
   case 524288.0:
      return (TP20);
   }
   return (TP20);
}

int count(int a_cmd_0) {
   int l_count_4 = 0;
   if (OrdersTotal() > 0) {
      for (g_ord_total_604 = OrdersTotal(); g_ord_total_604 >= 0; g_ord_total_604--) {
         OrderSelect(g_ord_total_604, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() == Symbol() && OrderType() == a_cmd_0 && OrderMagicNumber() == Magic) l_count_4++;
      }
      return (l_count_4);
   }
   return (0);
}
