/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/

#property indicator_separate_window
#property indicator_buffers 3
#property indicator_color1 Red
#property indicator_color2 Green
#property indicator_color3 Red

extern int LPeriod = 14;
double g_ibuf_80[];
double g_ibuf_84[];
double g_ibuf_88[];

int init() {
   if (ObjectType("FXUltraLabel") != 23) ObjectDelete("FXUltraLabel");
   if (ObjectFind("FXUltraLabel") == -1) ObjectCreate("FXUltraLabel", OBJ_LABEL, 0, Time[5], Close[5]);
   ObjectSetText("FXUltraLabel", "Secret Indicator Made 127,912$ in 2009!");
   ObjectSet("FXUltraLabel", OBJPROP_XDISTANCE, 20);
   ObjectSet("FXUltraLabel", OBJPROP_FONTSIZE, 12);
   ObjectSet("FXUltraLabel", OBJPROP_YDISTANCE, 20);
   if (ObjectType("FXUltraLabel2") != 23) ObjectDelete("FXUltraLabel2");
   if (ObjectFind("FXUltraLabel2") == -1) ObjectCreate("FXUltraLabel2", OBJ_LABEL, 0, Time[5], Close[5]);
   ObjectSetText("FXUltraLabel2", "Visit IndicatorForex.com!");
   ObjectSet("FXUltraLabel2", OBJPROP_XDISTANCE, 20);
   ObjectSet("FXUltraLabel2", OBJPROP_FONTSIZE, 12);
   ObjectSet("FXUltraLabel2", OBJPROP_YDISTANCE, 40);
   SetIndexStyle(0, DRAW_NONE);
   SetIndexBuffer(0, g_ibuf_80);
   SetIndexStyle(1, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(1, g_ibuf_84);
   SetIndexStyle(2, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(2, g_ibuf_88);
   IndicatorShortName("Volume Trend(" + LPeriod + ")");
   return (0);
}

int deinit() {
   return (0);
}

int start() {
   double ld_48;
   double ld_56;
   double ld_64;
   int l_bars_76;
   if (ObjectType("FXUltraLabel") != 23) ObjectDelete("FXUltraLabel");
   if (ObjectFind("FXUltraLabel") == -1) ObjectCreate("FXUltraLabel", OBJ_LABEL, 0, Time[5], Close[5]);
   ObjectSetText("FXUltraLabel", "Secret Indicator Made 127,912$ in 2009!");
   ObjectSet("FXUltraLabel", OBJPROP_XDISTANCE, 20);
   ObjectSet("FXUltraLabel", OBJPROP_FONTSIZE, 12);
   ObjectSet("FXUltraLabel", OBJPROP_YDISTANCE, 20);
   if (ObjectType("FXUltraLabel2") != 23) ObjectDelete("FXUltraLabel2");
   if (ObjectFind("FXUltraLabel2") == -1) ObjectCreate("FXUltraLabel2", OBJ_LABEL, 0, Time[5], Close[5]);
   ObjectSetText("FXUltraLabel2", "Visit IndicatorForex.com!");
   ObjectSet("FXUltraLabel2", OBJPROP_XDISTANCE, 20);
   ObjectSet("FXUltraLabel2", OBJPROP_FONTSIZE, 12);
   ObjectSet("FXUltraLabel2", OBJPROP_YDISTANCE, 40);
   double ld_unused_0 = 0;
   double ld_unused_8 = 0;
   double ld_16 = 0;
   double ld_24 = 0;
   double ld_32 = 0;
   double ld_40 = 0;
   int li_72 = IndicatorCounted();
   if (li_72 >= 0) {
      if (li_72 > 0) li_72--;
      l_bars_76 = Bars;
      for (int l_index_80 = 0; l_index_80 < l_bars_76; l_index_80++) {
         ld_16 = 0;
         ld_24 = 0;
         ld_32 = 0;
         ld_40 = 0;
         if (ld_16 == 0.0 && ld_24 == 0.0 && ld_32 == 0.0 && ld_40 == 0.0) {
            for (int l_count_84 = 0; l_count_84 < LPeriod; l_count_84++) {
               ld_16 += Volume[l_count_84 + l_index_80];
               ld_24 += (Volume[l_count_84 + l_index_80]) * l_count_84;
               ld_32 += l_count_84;
               ld_40 += l_count_84 * l_count_84;
            }
         } else {
            ld_16 -= Volume[l_index_80 - 1];
            ld_16 += Volume[LPeriod + l_index_80];
            ld_24 += (Volume[LPeriod + l_index_80]) * LPeriod;
            ld_32 += LPeriod;
            ld_40 += LPeriod * LPeriod;
         }
         ld_64 = ld_40 * LPeriod - ld_32 * ld_32;
         ld_56 = (ld_24 * LPeriod - ld_32 * ld_16) / ld_64;
         ld_48 = (ld_16 - ld_32 * ld_56) / LPeriod;
         g_ibuf_80[l_index_80] = -1.0 * ld_56;
         if (g_ibuf_80[l_index_80] > 0.0) g_ibuf_84[l_index_80] = g_ibuf_80[l_index_80];
         else g_ibuf_88[l_index_80] = g_ibuf_80[l_index_80];
      }
      return (0);
   }
}
